services:
  app:
    build:
      context: ./docker/php
    container_name: tasks_app
    volumes:
      - ./:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    container_name: tasks_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  node:
    build:
        context: ./docker/node
    container_name: tasks_node
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    volumes:
        - ./:/var/www/html
    ports:
        - "5173:5173"
    depends_on:
        - app

  mysql:
    image: mysql:8.0
    container_name: tasks_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: tasks_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
